### ISSUE TITLE
The 'lb.sticky-session.enabled=true' attribute does not work

### ISSUE THREAD

**Issue by zhangziru8088** [ran-jit/TomcatClusterRedisSessionManager#60]
I setted the 'lb.sticky-session.enabled=true' , however,when the redis was down, requests can not use jvm stored session values to process user requests and return  the error message: ‘tomcat.request.session.exception.BackendException: For some reason we couldn't process your request. Please contact system administrator for more details’.
the version :  tomcat-cluster-redis-session-manager-4.0.jar
please help me, thanks

**Comment by ran-jit** [comment]
Hi @zhangziru8088,

Is possible share the tomcat error log?

Thanks!

**Comment by ran-jit** [comment]
FYI - I tested the same in my test environment, and it's working fine.

Please add "redis.session.expiry.job.interval=<SESSION-TIMEOUT-IN-MINUTES>" in tomcat/conf/redis-data-cache.properties file and check the same.

I hope this helps. Thanks!

**Comment by zhangziru8088** [comment]
Dear Mr. ran-jit
   Set the properties 'redis.session.expiry.job.interval=100', the request cannot work when the Redis was down
The Error message: 'tomcat.request.session.exception.BackendException: For some reason we couldn't process your request. Please contact system administrator for more details.';

**Comment by ran-jit** [comment]
Hi @zhangziru8088,

Could you please share the `redis-data-cache.properties` and `tomcat/conf/web.xml` files?

Thanks!

**Comment by zhangziru8088** [comment]
HI Mr. ran-jit
 the configure file,please refer to the attached file. 

[conf.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/5807728/conf.zip)

**Comment by ran-jit** [comment]
Error opening attached file. Please check.. Thanks!

**Comment by zhangziru8088** [comment]
[conf.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/5812569/conf.zip)
Please try it，thanks

**Comment by ran-jit** [comment]
Please replace the attached `redis-data-cache.properties` file in your tomcat config and check the same.

[redis-data-cache.properties.zip](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/files/5815711/redis-data-cache.properties.zip)

I hope this helps. Thanks!

**Comment by zhangziru8088** [comment]
HI Mr.Ran-jit，
         Now it's ok, thank you very much.
         Another question, the response speed is very slow, how to reduce the response time? thanks again.

**Comment by ran-jit** [comment]
check the memory usage and network latency.

**Comment by ran-jit** [comment]
Hi @zhangziru8088,

Is redis and tomcat runs in same network?

And try increasing tomcat memory and check the same..

Thanks!

**Comment by zhangziru8088** [comment]
It's ok. thanks.
